### ISSUE TITLE
Instiallation failure with pip macOS Ventura 13.1 (22C65) - VS CODE bash

### ISSUE THREAD

**Issue by paritoshk** [dreji18/Bio-Epidemiology-NER#3]
PyMuPDF/setup.py: extra_link_args=[]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'fitz._fitz' extension
      swigging fitz/fitz.i to fitz/fitz_wrap.c
      swig -python -o fitz/fitz_wrap.c fitz/fitz.i
      error: command 'swig' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyMuPDF
  Running setup.py clean for PyMuPDF
Failed to build PyMuPDF
Installing collected packages: PyMuPDF, Bio-Epidemiology-NER
  Running setup.py install for PyMuPDF ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for PyMuPDF did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      PyMuPDF/setup.py: sys.argv: ['/private/var/folders/qh/mr12tldn3g76pnlklr517bsm0000gn/T/pip-install-6t5y85b5/pymupdf_089caf4c54124decbecd856b9651083b/setup.py', 'install', '--record', '/private/var/folders/qh/mr12tldn3g76pnlklr517bsm0000gn/T/pip-record-g_og8vnk/install-record.txt', '--single-version-externally-managed', '--compile', '--install-headers', '/opt/homebrew/Caskroom/miniforge/base/include/python3.10/PyMuPDF']
      PyMuPDF/setup.py: os.getcwd(): /private/var/folders/qh/mr12tldn3g76pnlklr517bsm0000gn/T/pip-install-6t5y85b5/pymupdf_089caf4c54124decbecd856b9651083b
      PyMuPDF/setup.py: __file__: /private/var/folders/qh/mr12tldn3g76pnlklr517bsm0000gn/T/pip-install-6t5y85b5/pymupdf_089caf4c54124decbecd856b9651083b/setup.py
      PyMuPDF/setup.py: $PYTHON_ARCH: None
      PyMuPDF/setup.py: os.environ (42):
      PyMuPDF/setup.py:     MANPATH: /opt/homebrew/share/man:
      PyMuPDF/setup.py:     TERM_PROGRAM: vscode
      PyMuPDF/setup.py:     TERM: xterm-256color
      PyMuPDF/setup.py:     SHELL: /bin/bash
      PyMuPDF/setup.py:     HOMEBREW_REPOSITORY: /opt/homebrew
      PyMuPDF/setup.py:     TMPDIR: /var/folders/qh/mr12tldn3g76pnlklr517bsm0000gn/T/
      PyMuPDF/setup.py:     CONDA_SHLVL: 1
      PyMuPDF/setup.py:     CONDA_PROMPT_MODIFIER: (base)
      PyMuPDF/setup.py:     TERM_PROGRAM_VERSION: 1.74.2
      PyMuPDF/setup.py:     ORIGINAL_XDG_CURRENT_DESKTOP: undefined
      PyMuPDF/setup.py:     MallocNanoZone: 0
      PyMuPDF/setup.py:     USER: paritoshmacmini
      PyMuPDF/setup.py:     COMMAND_MODE: unix2003
      PyMuPDF/setup.py:     CONDA_EXE: /opt/homebrew/Caskroom/miniforge/base/bin/conda
      PyMuPDF/setup.py:     SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.O6empSllv6/Listeners
      PyMuPDF/setup.py:     __CF_USER_TEXT_ENCODING: 0x1F5:0x0:0x0
      PyMuPDF/setup.py:     _CE_CONDA:
      PyMuPDF/setup.py:     PATH: /opt/homebrew/Caskroom/miniforge/base/bin:/opt/homebrew/Caskroom/miniforge/base/condabin:/opt/homebrew/opt/curl/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/opt/curl/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
      PyMuPDF/setup.py:     CONDA_PREFIX: /opt/homebrew/Caskroom/miniforge/base
      PyMuPDF/setup.py:     __CFBundleIdentifier: com.microsoft.VSCode
      PyMuPDF/setup.py:     PWD: /Users/paritoshmacmini/Documents/antiagingintegratedinformationsystem/antiaging
      PyMuPDF/setup.py:     LANG: en_US.UTF-8
      PyMuPDF/setup.py:     VSCODE_GIT_ASKPASS_EXTRA_ARGS: --ms-enable-electron-run-as-node
      PyMuPDF/setup.py:     XPC_FLAGS: 0x0
      PyMuPDF/setup.py:     _CE_M:
      PyMuPDF/setup.py:     XPC_SERVICE_NAME: 0
      PyMuPDF/setup.py:     SHLVL: 1
      PyMuPDF/setup.py:     HOME: /Users/paritoshmacmini
      PyMuPDF/setup.py:     VSCODE_GIT_ASKPASS_MAIN: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
      PyMuPDF/setup.py:     HOMEBREW_PREFIX: /opt/homebrew
      PyMuPDF/setup.py:     DYLD_LIBRARY_PATH: :/opt/local/lib
      PyMuPDF/setup.py:     CONDA_PYTHON_EXE: /opt/homebrew/Caskroom/miniforge/base/bin/python
      PyMuPDF/setup.py:     LOGNAME: paritoshmacmini
      PyMuPDF/setup.py:     VSCODE_GIT_IPC_HANDLE: /var/folders/qh/mr12tldn3g76pnlklr517bsm0000gn/T/vscode-git-3acd473be0.sock
      PyMuPDF/setup.py:     CONDA_DEFAULT_ENV: base
      PyMuPDF/setup.py:     INFOPATH: /opt/homebrew/share/info:
      PyMuPDF/setup.py:     HOMEBREW_CELLAR: /opt/homebrew/Cellar
      PyMuPDF/setup.py:     VSCODE_GIT_ASKPASS_NODE: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)
      PyMuPDF/setup.py:     GIT_ASKPASS: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
      PyMuPDF/setup.py:     COLORTERM: truecolor
      PyMuPDF/setup.py:     _: /opt/homebrew/Caskroom/miniforge/base/bin/pip
      PyMuPDF/setup.py:     PIP_BUILD_TRACKER: /private/var/folders/qh/mr12tldn3g76pnlklr517bsm0000gn/T/pip-build-tracker-ym6c8s6t
      running install
      /opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running build_ext
      building 'fitz._fitz' extension
      swigging fitz/fitz.i to fitz/fitz_wrap.c
      swig -python -o fitz/fitz_wrap.c fitz/fitz.i
      error: command 'swig' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> PyMuPDF

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by paritoshk** [comment]
It seems like the pytes is not feasible - please allow two different installations for those who have raw text instead of PDF to create a lighter and faster install!

**Comment by dreji18** [comment]
Yes, there is a chance, it will apply conflict in the case of PyMuPDF, 

Try uninstalling both PyMuPDF & fitz

install PyMuPDF==1.20.1

**Comment by paritoshk** [comment]
it was resolved with ' brew install swig '
