### ISSUE TITLE
Can I get a list of all entities it detects?

### ISSUE THREAD

**Issue by BhavyaShah1234** [dreji18/Bio-Epidemiology-NER#4]
Great work! 
Can I get a list of all the entities(classes) that it detects?
Like disease, history, etc

**Comment by dreji18** [comment]
Hi, Thanks. You can find the list here in this config file

https://huggingface.co/d4data/biomedical-ner-all/blob/main/config.json

**Comment by BhavyaShah1234** [comment]
Thanks
