### ISSUE TITLE
Repurpose this model for other domains 

### ISSUE THREAD

**Issue by mysteryjeans** [dreji18/Bio-Epidemiology-NER#5]
Need help to understand how can I repurpose this model or start with distilbert to recognise certain phrases in call recording transcript (in call center) like "Thank you for calling XX [Your call may be record (disclaimer)]" phrase "Your call may be recorded" is a disclaimer.

**Comment by dreji18** [comment]
Hi, I would suggest not repurposing this model for your use case, since its purely trained on Biomedical data
